# Generated by Django 3.2 on 2021-05-14 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('brand_type', models.CharField(choices=[('B', 'Budget'), ('P', 'Premium'), ('S', 'Super Premiun')], max_length=1)),
                ('location', models.CharField(choices=[('N', 'National'), ('I', 'Inter National'), ('M', 'Multi National')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('count_in_stock', models.PositiveSmallIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_cod_available', models.BooleanField(default=True, verbose_name='COD Available')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('sales', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.brand')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposability', models.CharField(choices=[('1D', 'Single Day'), ('2W', 'Two Weeks'), ('1M', 'One Month'), ('3M', 'Quater Year'), ('1Y', 'One Year')], max_length=2)),
                ('colur', models.CharField(blank=True, max_length=24, null=True)),
                ('diameter', models.DecimalField(decimal_places=1, max_digits=3)),
                ('base_curve', models.DecimalField(decimal_places=1, max_digits=3)),
                ('material', models.CharField(max_length=32)),
                ('power_type', models.CharField(blank=True, choices=[('1', 'type 1'), ('2', 'type 2')], max_length=4, null=True)),
                ('power_range_low', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('power_range_high', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'verbose_name': 'Contact Lens',
                'verbose_name_plural': 'Contact Lenses',
            },
        ),
    ]
