# Generated by Django 3.2 on 2021-05-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210515_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlens',
            name='content_in_box',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
