# Generated by Django 3.2 on 2021-05-15 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactlens_content_in_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex')], max_length=1)),
                ('is_for_kids', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('S', 'Sunglass'), ('C', 'Computer'), ('S', 'Reading Glasses'), ('N', 'Casual')], max_length=10)),
                ('material_type', models.CharField(choices=[('M', 'Metalic'), ('P', 'Plastic'), ('B', 'Mixed')], max_length=1)),
                ('frame_material', models.CharField(blank=True, max_length=64, null=True)),
                ('temple_material', models.CharField(blank=True, max_length=64, null=True)),
                ('frame_style', models.CharField(blank=True, max_length=32, null=True)),
                ('frame_color', models.CharField(blank=True, max_length=32, null=True)),
                ('frame_width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lens_height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lens_weidth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frame_weight', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('prescription_type', models.CharField(blank=True, max_length=60, null=True)),
                ('power_range_low', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('power_range_high', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'verbose_name_plural': 'Glasses',
            },
        ),
    ]
