# Generated by Django 3.2 on 2021-05-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
