# Generated by Django 3.2 on 2021-05-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='Vineet Mahajan', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
    ]
