# Generated by Django 3.2 on 2021-05-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210515_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pnone_no',
            new_name='phone_no',
        ),
    ]
