# Generated by Django 3.2 on 2021-04-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_key_generated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
