# Generated by Django 3.2 on 2021-05-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_pnone_no_account_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
