# Generated by Django 3.2 on 2021-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210415_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_verified',
            new_name='is_email_verified',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='key_generated_at',
            new_name='unique_key_time',
        ),
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
